name: Conditionals

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: run on release
        if: github.ref == 'refs/heads/release'
        run: echo "This is the release branch"

      - name: Only runs on pull_request and prints the PR title and PR author’s username
        if: github.event_name == 'pull_request'
        run: "This is a pull request - ${{ github.triggering_actor }}"
