name: Conditionals

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: run on release
        if: github.ref == 'refs/heads/release'
        run: echo "This is the release branch"

      - name: Only runs on pull_request and prints the PR title and PR author’s username
        if: github.event_name == 'pull_request'
        run: echo "This is a pull request called ${{ github.event.pull_request.title }} by ${{ github.triggering_actor }}"

      - name: executes only if the commit message includes the keyword [run-tests]
        if: contains(github.event.head_commit.message, 'run-tests')
        run: echo "Executing tests as requested..."

      - name: Repository Owner Verification
        if: github.repository_owner == github.triggering_actor
        run: echo "Running because repo owner ${{ github.repository_owner }} == triggering user ${{ github.triggering_actor }}"
        
